name: Build Snapshot

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: Snapshot Artifacts
          path: ./build/libs/
